version: '3.8'

services:
  banco-marfil-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banco-marfil-demo
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped