version: '3.8'

services:
  banco-marfil-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: banco-marfil-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped